In [97]:
import numpy as np
import random
def LoShuGame():
    # counter to track results
    # index 0 is for victory and 1 is for lost game
    result=[0,0]
    print('-----------------------------------------------')
    #loop to repeat the game
    while True:
        i = int(input('Enter 1 for integer inputs to array or 2 for random array values,anything else to exit: '))
        if i==1:
            grid=[] # store 3x3 array

            # taking array values
            for i in range(1,4):
                for j in range(1,4):
                    temp = int(input(f"Enter Grid Value (between 1-9) at index {i},{j}: "))
                    if temp<=9 and temp >=1: # validation for input values
                        grid.append(temp)  
                    else:
                        # raise exception if input > 9 or <1
                        raise Exception("Sorry, wrong input is given")

            Matrix =np.resize(grid,(3,3)) # converting list to 3x3 array
        elif i==2:
            # creating a 3x3 array with random values between 1(including) to 10(excluding)
            Matrix = np.random.randint(low=1,high=10, size=(3, 3))
        else:
            print('Thank You for Playing the Game')
            break

        # store sum of individual rows ,column,and diagonal elements
        SumList=[]

        # find the sum of individual row and append into list
        SumList.append(sum(Matrix[0])) 
        SumList.append(sum(Matrix[1]))
        SumList.append(sum(Matrix[2]))

        # find the sum of individual column and append into list
        SumList.append(sum(Matrix[:,0]))
        SumList.append(sum(Matrix[:,1]))
        SumList.append(sum(Matrix[:,2]))

        # find the sum of diagonal element and 
        SumList.append(Matrix[0,0] + Matrix[1,1] + Matrix[2,2])
        SumList.append(Matrix[2,0] + Matrix[1,1] + Matrix[0,2])

        print('Array is: ')
        print(Matrix)

        # converting list SumList to SET to find the unique elements
        # if unique element is 1 i.e all sums are equal
        # hence it is Lo Shu Magic Square

        if len(set(SumList))==1:
            result[0] = result[0]+1 # updating the result
            print('Its Lo Shu Magic Square ')
            print('Overall result:-','Won: ',result[0],' ','Lost: ',result[1])
            print('-----------------------------------------------')
        else:
            result[1] = result[1]+1 # updating the result
            print('Its not Lo Shu Magic Square ')
            print('Overall result:-','Won: ',result[0],' ','Lost: ',result[1])
            print('-----------------------------------------------')

In [98]:
LoShuGame()

-----------------------------------------------
Enter 1 for integer inputs to array or 2 for random array values,anything else to exit: 1
Enter Grid Value (between 1-9) at index 1,1: 4
Enter Grid Value (between 1-9) at index 1,2: 9
Enter Grid Value (between 1-9) at index 1,3: 2
Enter Grid Value (between 1-9) at index 2,1: 3
Enter Grid Value (between 1-9) at index 2,2: 5
Enter Grid Value (between 1-9) at index 2,3: 7
Enter Grid Value (between 1-9) at index 3,1: 8
Enter Grid Value (between 1-9) at index 3,2: 1
Enter Grid Value (between 1-9) at index 3,3: 6
Array is: 
[[4 9 2]
 [3 5 7]
 [8 1 6]]
Its Lo Shu Magic Square 
Overall result:- Won:  1   Lost:  0
-----------------------------------------------
Enter 1 for integer inputs to array or 2 for random array values,anything else to exit: 2
Array is: 
[[2 2 2]
 [2 8 2]
 [3 5 1]]
Its not Lo Shu Magic Square 
Overall result:- Won:  1   Lost:  1
-----------------------------------------------
Enter 1 for integer inputs to array or 2 for rand

In [ ]:
2
