In [52]:
# import library
import numpy as np
import scipy.linalg as la

In [53]:
# define function to generate A
def A(n):
    array = []
    for i in range(1,n+1):
        row=[]
        for j in range(i,n+i):
            row.append(1/j) # store row value
        array.append(row)
    array = np.resize(array,(n,n))
    return array

In [54]:
# define function to generate b
def b(n):
    Barray=[]
    for i in range(n):
        Barray.append((-1)**i) # even position -1,and odd position value will be 1.
    return np.array(Barray).T

In [55]:
A(3) # generate A(3)

array([[1.        , 0.5       , 0.33333333],
       [0.5       , 0.33333333, 0.25      ],
       [0.33333333, 0.25      , 0.2       ]])

In [56]:
b(3) # generate b(3)

array([ 1, -1,  1])

In [57]:
x = la.solve(A(2),b(2)) # solve for n=2
print(x)

[ 10. -18.]


In [58]:
x = la.solve(A(4),b(4))   # solve for n=4
print(x)

[  516. -5700. 13620. -8820.]


In [59]:
x = la.solve(A(8),b(8))  # solve for n=8
print(x)

[ 8.68359956e+05 -4.63836215e+07  6.04807527e+08 -3.27135713e+09
  8.80667121e+09 -1.24630499e+10  8.87175036e+09 -2.50393557e+09]


In [60]:
x = la.solve(A(16),b(16))   # solve for n=16
print(x)

[-4.35066043e+09  6.88399692e+11 -2.67146622e+13  4.43786597e+14
 -3.90690883e+15  2.01518306e+16 -6.34080381e+16  1.20411958e+17
 -1.27184793e+17  6.69570572e+16 -8.58448767e+16  2.96030856e+17
 -4.94416979e+17  4.24004292e+17 -1.87259615e+17  3.40474645e+16]


<ipython-input-60-048b9a6faf4b>:1: LinAlgWarning: Ill-conditioned matrix (rcond=7.09847e-19): result may not be accurate.
  x = la.solve(A(16),b(16))   # solve for n=16
